[[main]]
name = "All Projects"
pageRef = "projects"
weight = 1

[[main]]
name = "Cthulhu and Me"
parent = "All Projects"
pageRef = "cthulhu-and-me"
weight = 1

[[main]]
name = "GPU Flocking"
parent = "All Projects"
pageRef = "gpu-flocking"
weight = 2

[[main]]
name = "Spline Tools"
parent = "All Projects"
pageRef = "spline-tools"
weight = 3

[[footer]]
none = "none"
